name: nodejs-ci
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    unit-tests:
        strategy:
            matrix:
                node-version: [14.x, 22.x]
                os: [ubuntu-latest, windows-latest, macos-latest]
                exclude:
                    - node-version: 14.x
                      os: macos-latest
            fail-fast: false
            max-parallel: 2
        runs-on: ${{ matrix.os }}
        env:
            PORT: 4000
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: '${{ matrix.node-version }}'
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
            
            - name: Set env variable for port linux 
              if: runner.os == 'Linux' || runner.os == 'macOS'
              run: export PORT=${{ env.PORT }}
            - name: Set env variable for port windows
              if: runner.os == 'windows'
              run: Set-Variable -Name port -Value ${{ env.PORT }}
    Coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                node-version: '22.x'
            - name: Install dependencies
              run: npm install
            - name: Run tests with coverage
              run: npm run coverage
            - name: Upload coverage Artifact
              uses: actions/upload-artifact@v7
              with:
                name: coverage-report
                path: coverage/
              
